del langX$1.class
del langX$JJCalls.class
del langX$LookaheadSuccess.class
del langX.class
del langX.java
del langXConstants.class
del langXConstants.java
del langXTokenManager.class
del langXTokenManager.java
del ParseException.class
del ParseException.java
del SimpleCharStream.class
del SimpleCharStream.java
del Token.class
del TokenMgrError.class
del TokenMgrError.java
del TokenMgrError.java
del Token.java
javacc langX++.jj
