/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int READ = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SUPER = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int BOOLEAN = 27;
  /** RegularExpression Id. */
  int DOUBLE = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int SWITCH = 30;
  /** RegularExpression Id. */
  int DO = 31;
  /** RegularExpression Id. */
  int CASE = 32;
  /** RegularExpression Id. */
  int DEFAULT1 = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int int_constant = 35;
  /** RegularExpression Id. */
  int string_constant = 36;
  /** RegularExpression Id. */
  int null_constant = 37;
  /** RegularExpression Id. */
  int FLOATCONSTANT = 38;
  /** RegularExpression Id. */
  int CHARCONSTANT = 39;
  /** RegularExpression Id. */
  int BOOLEANCONSTANT = 40;
  /** RegularExpression Id. */
  int IDENT = 41;
  /** RegularExpression Id. */
  int LETTER = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int LPAREN = 44;
  /** RegularExpression Id. */
  int RPAREN = 45;
  /** RegularExpression Id. */
  int LBRACE = 46;
  /** RegularExpression Id. */
  int RBRACE = 47;
  /** RegularExpression Id. */
  int LBRACKET = 48;
  /** RegularExpression Id. */
  int RBRACKET = 49;
  /** RegularExpression Id. */
  int SEMICOLON = 50;
  /** RegularExpression Id. */
  int COMMA = 51;
  /** RegularExpression Id. */
  int DOT = 52;
  /** RegularExpression Id. */
  int DOISPONTOS = 53;
  /** RegularExpression Id. */
  int ASPAS = 54;
  /** RegularExpression Id. */
  int UNDERSCORE = 55;
  /** RegularExpression Id. */
  int ASSIGN = 56;
  /** RegularExpression Id. */
  int GT = 57;
  /** RegularExpression Id. */
  int LT = 58;
  /** RegularExpression Id. */
  int EQ = 59;
  /** RegularExpression Id. */
  int LE = 60;
  /** RegularExpression Id. */
  int GE = 61;
  /** RegularExpression Id. */
  int NEQ = 62;
  /** RegularExpression Id. */
  int PLUS = 63;
  /** RegularExpression Id. */
  int MINUS = 64;
  /** RegularExpression Id. */
  int STAR = 65;
  /** RegularExpression Id. */
  int SLASH = 66;
  /** RegularExpression Id. */
  int REM = 67;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 68;
  /** RegularExpression Id. */
  int INVALID_CONST = 69;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "\"while\"",
    "\"switch\"",
    "\"do\"",
    "\"case\"",
    "\"default\"",
    "\"float\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<FLOATCONSTANT>",
    "<CHARCONSTANT>",
    "<BOOLEANCONSTANT>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"\\\"\"",
    "\"_\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
